version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
  docker: circleci/docker@2.6.0
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/indexads
          tag: $DOCKER_LOGIN/indexads:latest
          filters:
            branches:
              only: main
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          path: ./infrastructure
          checkout: true
          context: terraform
      - terraform/validate:
          path: ./infrastructure
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          path: ./infrastructure
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          path: ./infrastructure
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
