version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
  docker: circleci/docker@2.6.0
workflows:      
  deploy_infrastructure:
    jobs:
      - docker/publish:
          image: ${DOCKER_LOGIN}/indexads
          tag: ${DOCKER_LOGIN}/indexads:latest
          filters:
            branches:
              only: main
      - terraform/fmt:
          path: ./infrastructure
          checkout: true
          context: terraform
          requires:
            - docker/publish
      - terraform/validate:
          path: ./infrastructure
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          path: ./infrastructure
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          path: ./infrastructure
          attach-workspace: true
          context: terraform
          requires:
            - terraform/plan
